# Generated by Django 3.2 on 2022-08-10 12:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CoixExp',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gene', models.TextField(blank=True, null=True)),
                ('sample_id', models.TextField(blank=True, null=True)),
                ('fpkm', models.FloatField(blank=True, null=True)),
                ('tpm', models.FloatField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='CoixSamp',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sample_id', models.TextField(blank=True, null=True)),
                ('sample_download_link', models.TextField(blank=True, null=True)),
                ('sample_tissue', models.TextField(blank=True, null=True)),
                ('sample_project_number', models.TextField(blank=True, null=True)),
                ('sample_description', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='ZeaExp',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gene', models.TextField(blank=True, null=True)),
                ('sample_id', models.TextField(blank=True, null=True)),
                ('fpkm', models.FloatField(blank=True, null=True)),
                ('tpm', models.FloatField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='ZeaSamp',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sample_id', models.TextField(blank=True, null=True)),
                ('sample_download_link', models.TextField(blank=True, null=True)),
                ('sample_tissue', models.TextField(blank=True, null=True)),
                ('sample_project_number', models.TextField(blank=True, null=True)),
                ('sample_description', models.TextField(blank=True, null=True)),
            ],
        ),
    ]
